version: "3.8"

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - 3000:3000
    depends_on: server
    networks:
      - ghettohustler_network

  server:
    build:
      context: ./server
    env_file: ./server/.env
    container_name: server
    networks:
      - ghettohustler_network
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - ghettohustler_network

  redis:
    image: redis:6.2.4-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - ghettohustler_network
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

networks:
  ghettohustler_network:
    driver: bridge
    name: ghettohustler_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
