version: "3.9"

services:
  webserver:
    image: webserver
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
    ports:
      - "80:80"

  nextjs:
    image: nextjs
    container_name: nextjs
    restart: unless-stopped
    ports:
      - 3000:3000

  server:
    image: server
    restart: unless-stopped
    container_name: server
    ports:
      - 8080:8080

  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    container_name: postres_database
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - network

  redis:
    image: redis:6.2.1-alpine
    container_name: redis_database
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
